<#
Analyze `cpu-sample.csv` generated by automated sampling.
Produces average CPU and peak working set per PID/process.
#>

param(
    [string]$CpuCsvPath = "$(Join-Path $env:APPDATA 'Antigravity-auto-repair-backup-*/cpu-sample.csv')"
)

if (-not (Test-Path $CpuCsvPath)) { Write-Error "cpu sample file not found: $CpuCsvPath"; exit 1 }

$data = Import-Csv -Path $CpuCsvPath -ErrorAction Stop

$summary = $data | Group-Object ProcessName | ForEach-Object {
    $avgCpu = ($_.Group | Measure-Object -Property CPUSeconds -Average).Average
    $maxWs = ($_.Group | Measure-Object -Property WorkingSetMB -Maximum).Maximum
    [PSCustomObject]@{ ProcessName=$_.Name; AvgCPU=$avgCpu; PeakWS_MB=$maxWs }
}

$summary | Sort-Object -Property AvgCPU -Descending | Format-Table -AutoSize
