import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';

/// LEVEL B (SUPPORT LAYER): Centralized Export Engine.
/// Deduplicates formatting logic for sharing & copying StructuredMealCards.
/// Ensures missing keys are gracefully handled and non-user-friendly metadata (JSON arrays) are stripped out.
class RecipeExportService {
  
  /// Generates the raw social-friendly text representation of a StructuredMealCard JSON limit.
  static String formatRecipePayload(Map<String, dynamic> card) {
    final title = card['title'] ?? 'Delicious Meal Concept';
    final time = card['time'] ?? 'N/A';
    final cuisine = card['cuisine'] ?? 'Fusion';
    final matchType = card['match_type'] ?? 'General Match';

    // Build the Header
    final buffer = StringBuffer();
    buffer.writeln('🍽️ $title');
    buffer.writeln('⏱️ Time: $time | 🌍 Cuisine: $cuisine | ✨ $matchType');
    buffer.writeln();

    // Trace explanation (Why this?)
    final traces = List<String>.from(card['ai_explanation_trace'] ?? []);
    if (traces.isNotEmpty) {
      buffer.writeln('🤔 Why this recipe?');
      buffer.writeln(traces.first);
      buffer.writeln();
    }

    // Used Pantry Items
    final inventoryItems = List<dynamic>.from(card['used_inventory_ingredients'] ?? []);
    if (inventoryItems.isNotEmpty) {
      buffer.writeln('✅ From the Pantry:');
      for (final item in inventoryItems) {
        final i = item as Map<String, dynamic>? ?? {};
        final sub = i['is_substitution'] == true ? ' (Sub for ${i['substitution_for']})' : '';
        buffer.writeln(' • ${i['name'] ?? 'Unknown'} - ${i['quantity'] ?? ''} ${i['unit'] ?? ''}$sub');
      }
      buffer.writeln();
    }

    // Missing Items / Shopping Deficits
    final deficits = List<dynamic>.from(card['missing_shopping_deficits'] ?? []);
    if (deficits.isNotEmpty) {
      buffer.writeln('🛒 Shopping Deficits:');
      for (final item in deficits) {
        final i = item as Map<String, dynamic>? ?? {};
        buffer.writeln(' • ${i['name'] ?? 'Unknown'} - ${i['quantity'] ?? ''} ${i['unit'] ?? ''}');
      }
      buffer.writeln();
    }

    // Compliance Warning
    final compliance = card['compliance'] as Map<String, dynamic>? ?? {};
    final isSafe = compliance['is_compliant'] == true;
    if (!isSafe) {
      buffer.writeln('⚠️ SAFETY WARNING:');
      buffer.writeln(compliance['explanation']?.toString() ?? 'Contains restricted ingredients based on your profile.');
      buffer.writeln();
    }

    buffer.writeln('— Generated by GS FOOD 🤖');

    return buffer.toString();
  }

  /// Exports via the Clipboard API natively natively.
  static Future<bool> copyToClipboard(Map<String, dynamic> card) async {
    try {
      final text = formatRecipePayload(card);
      await Clipboard.setData(ClipboardData(text: text));
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Exports via the OS-level Native Share Sheet (which targets WhatsApp, Messages, Email, etc.)
  static Future<bool> shareToSocial(Map<String, dynamic> card) async {
    try {
      final text = formatRecipePayload(card);
      // OS Share Sheet explicitly exposes WhatsApp if installed
      final result = await Share.shareWithResult(text, subject: 'GS FOOD Recipe: ${card['title'] ?? ''}');
      return result.status == ShareResultStatus.success;
    } catch (e) {
      return false;
    }
  }
}
